name: ci

on:
  push:
    branches:
      - master       # Only trigger on push to 'master'
  pull_request:
    branches:
      - master       # Only trigger PRs targeting 'master'

jobs:
  build:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu environment

    steps:
      # Step 1: Checkout code from the 'master' branch
      - name: Checkout code
        run: |
          git clone https://github.com/${{ github.repository }} .
          git fetch --all
          git checkout master

      # Step 2: Push changes back to 'master' (if needed)
      - name: Push changes to repository
        run: |
          git config --global user.email "jakkasrishanthreddy.com"
          git config --global user.name "Qzin-10"
          git add .
          git commit -m "Update after build" || echo "No changes to commit"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
