name: ci

on:
  push:
    branches:
      - main         # Trigger on push to the 'main' branch
      - feature/*    # Trigger on push to any branch starting with 'feature/'
  pull_request:
    branches:
      - main         # Trigger on PR targeting the 'main' branch
      - feature/*    # Trigger on PR to 'main' from 'feature/*' branches

jobs:
  build:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu environment

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Pull the latest changes (to ensure we have the latest updates)
      - name: Pull latest changes
        run: git pull origin ${{ github.ref }}

      # Step 3: Push changes back to the repository (if needed)
      - name: Push changes to repository
        run: |
          git config --global user.email "jakkasrishanthreddy.com"
          git config --global user.name "Qzin-10"
          git add .
          git commit -m "Update after build"
          git push origin ${{ github.ref }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use GitHub token for authentication
